databases:
  - name: actapi
    databaseName: actdb_ygx2
    user: actdb_ygx2
    plan: free

services:
  - type: web
    name: actapi
    runtime: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: actapi
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false 
      - key: WEB_CONCURRENCY
        value: 2