---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: list appointments
      tags:
      - Appointments
      responses:
        '200':
          description: successful
  "/api/v1/enquiries":
    get:
      summary: list enquiries
      tags:
      - Enquiries
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: https://act-api-v2.onrender.com/api-docs
