openapi: 3.0.1
info:
  title: Act Immigration API
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: List all appointments
      description: Retrieve all appointments belonging to the authenticated user.
      tags:
      - Appointments
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Appointments retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Appointment"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    post:
      summary: Create a new appointment
      description: Create a new appointment associated with the authenticated user.
      tags:
      - Appointments
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Appointment"
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
                surname:
                  type: string
                  example: Doe
                phonenumber:
                  type: string
                  example: "+1234567890"
                email:
                  type: string
                  example: john.doe@example.com
                service_type:
                  type: string
                  example: Immigration Consultation
                venue:
                  type: string
                  example: Main Office
                appointment_date:
                  type: string
                  format: date
                  example: '2025-01-10'
                appointment_type:
                  type: string
                  example: Virtual
              required:
              - name
              - surname
              - phonenumber
              - email
              - service_type
              - venue
              - appointment_date
              - appointment_type
  # The rest of the paths remain unchanged...

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John
        surname:
          type: string
          example: Doe
        phonenumber:
          type: string
          example: "+1234567890"
        email:
          type: string
          example: john.doe@example.com
        service_type:
          type: string
          example: Immigration Consultation
        venue:
          type: string
          example: Main Office
        appointment_date:
          type: string
          format: date
          example: "2025-01-10"
        appointment_type:
          type: string
          example: Virtual
        created_at:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
    Enquiry:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John
        surname:
          type: string
          example: Doe
        phonenumber:
          type: string
          example: "+123456789"
        email:
          type: string
          example: john.doe@example.com
        gender:
          type: string
          example: Male
        dob:
          type: string
          format: date
          example: "1990-01-01"
        marital_status:
          type: string
          example: Single
        residential_address:
          type: string
          example: 123 Main Street
        entry_date:
          type: string
          format: date
          example: "2022-01-01"
        passport_number:
          type: string
          example: A12345678
        reference_number:
          type: string
          example: REF001
        service_type:
          type: string
          example: Immigration Consultation
        elaborate:
          type: string
          example: Details of the enquiry
        immigration_status:
          type: string
          example: Pending
        created_at:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
    Error:
      type: object
      properties:
        error:
          type: string
          example: Unauthorized access
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: https://act-api-v2.onrender.com/api-docs
